package com.app.studysnap.model;

/**
 * A model class representing a single quiz attempt made by a user.
 * <p>
 * Each attempt records the user and quiz IDs, a display-form score (e.g. "8/10"),
 * the time taken in seconds, and a timestamp string indicating when the attempt occurred.
 * </p>
 */
public class Attempt {
    private int attemptId;
    private int userId;
    private int quizId;
    private String score;
    private int timeTaken;
    private String attemptAt;

    /**
     * Constructs a new {@code Attempt} without a predefined attempt ID.
     * <p>
     * Use this constructor when creating a new attempt prior to persistence,
     * where the ID will typically be generated by the database.
     * </p>
     * @param userId The ID of the user who took the quiz
     * @param quizId The ID of the quiz that was attempted
     * @param score The display score for this attempt (e.g. {@code "8/10"})
     * @param timeTaken The total time taken in seconds to complete the quiz
     * @param attemptAt The timestamp of the attempt as a formatted string (e.g. {@code "yyyy-MM-dd HH:mm:ss"})
     */
    public Attempt(int userId, int quizId, String score, int timeTaken, String attemptAt){
        this.userId = userId;
        this.quizId = quizId;
        this.score = score;
        this.timeTaken = timeTaken;
        this.attemptAt = attemptAt;
    }

    /**
     * Constructs a new {@code Attempt} with an explicit attempt ID.
     * <p>
     * Use this constructor when feeding from storage where the ID is already known.
     * </p>
     * @param attemptId The unique identifier of this attempt
     * @param userId The ID of the user who took the quiz
     * @param quizId The ID of the quiz that was attempted
     * @param score The display score for this attempt (e.g. {@code "8/10"})
     * @param timeTaken The total time taken in seconds to complete the quiz
     * @param attemptAt The timestamp of the attempt as a formatted string (e.g. {@code "yyyy-MM-dd HH:mm:ss"})
     */
    public Attempt(int attemptId, int userId, int quizId, String score, int timeTaken, String attemptAt) {
        this.attemptId = attemptId;
        this.userId = userId;
        this.quizId = quizId;
        this.score = score;
        this.timeTaken = timeTaken;
        this.attemptAt = attemptAt;
    }

    // Getters

    /**
     * @return The unique identifier of this attempt
     */
    public int getAttemptId() { return attemptId; }

    /**
     * @return The ID of the user who took the quiz
     */
    public int getUserId() { return userId; }

    /**
     * @return The ID of the quiz that was attempted
     */
    public int getQuizId() { return quizId; }

    /**
     * @return The display score for this attempt (e.g. {@code "8/10"})
     */
    public String getScore() { return score; }

    /**
     * @return The total time taken in seconds to complete the quiz
     */
    public int getTimeTaken() { return timeTaken; }

    /**
     * @return The timestamp of the attempt as a formatted string
     */
    public String getAttemptAt() { return attemptAt; }

    // Setters

    /**
     * Sets the unique identifier of this attempt.
     * @param attemptId The attempt ID
     */
    public void setAttemptId(int attemptId) { this.attemptId = attemptId; }

    /**
     * Sets the user ID associated with this attempt.
     * @param userId The user ID
     */
    public void setUserId(int userId) { this.userId = userId; }

    /**
     * Sets the quiz ID associated with this attempt.
     * @param quizId The quiz ID
     */
    public void setQuizId(int quizId) { this.quizId = quizId; }

    /**
     * Sets the display score for this attempt.
     * @param score The score string (e.g. {@code "8/10"})
     */
    public void setScore(String score) { this.score = score; }

    /**
     * Sets the total time taken in seconds to complete the quiz.
     * @param timeTaken Time in seconds
     */
    public void setTimeTaken(int timeTaken) { this.timeTaken = timeTaken; }

    /**
     * Sets the timestamp of the attempt.
     * @param attemptAt The timestamp string (e.g. {@code "yyyy-MM-dd HH:mm:ss"})
     */
    public void setAttemptAt(String attemptAt) { this.attemptAt = attemptAt; }
}